### ISSUE TITLE
504 Gateway ->isAuthenticated

### ISSUE THREAD

**Issue by stouch** [Happyr/LinkedIn-API-client#161]
| Q                       | A
| ----------------------- | ---
| Bug?                    | yes
| New Feature?            | no
| Are you using composer? | yes
| Version                 | latest

I've got big trouble with 504 Gateway error on my production site where I use your great library since a long time. But since today (~ 2h PM GMT+2), impossible to execute $linkedIn->isAuthenticated() (504 gateway).

So i tried the below basic code on a local vhost (http://tests.local) :
```
<?php

include('vendor/autoload.php');

$linkedIn=new Happyr\LinkedIn\LinkedIn(  <ID>  , <SECRET> );

if ($linkedIn->isAuthenticated()) {
    //we know that the user is authenticated now. Start query the API
    $user=$linkedIn->get('v1/people/~:(firstName,lastName)');
    echo "Welcome ".$user['firstName'];

    exit();
} elseif ($linkedIn->hasError()) {
    echo "User canceled the login.";
    exit();
}

//if not authenticated
$url = $linkedIn->getLoginUrl(array('redirect_uri' => 'http://tests.local'));
echo "<a href='$url'>Login with LinkedIn</a>";
```

Same problem... 504.

Can you help me ?

Thank you.

**Comment by zscaiosi** [comment]
I am experiencing the same as @stouch, around 14:00 while I was implementing some changes not related to Linkedin API I realized that it was not possible to my users to log in using LinkedIn API anymore.

They get stuck in the Auth process.
@Nyholm or @cakper could you help us?

**Comment by leonardobaggio** [comment]
we are also facing this error, our production website that was running fine started to display an error since the past hours:

LinkedInTransferException:
Error while requesting data from LinkedIn.com: transfer closed with outstanding read data remaining
--
 at RequestManager->sendRequest('GET', 'https://api.linkedin.com/v1/people/~:(id,firstName,lastName)?format=json', array('Authorization' => 'Bearer [token hidden]', 'Content-Type' => 'application/json', 'x-li-format' => 'json'), null)

**Comment by stouch** [comment]
It looks like the problem has been resolved , it was probably a bug from Linkedin API.
I'll just wait few days to be sure before closing this issue.

**Comment by zscaiosi** [comment]
@stouch nice!

I was implementing a "hard coded" auth process for my app, thereby I am gonna hold on too.
