### ISSUE TITLE
Getting error after install php

### ISSUE THREAD

**Issue by aditya-** [Happyr/LinkedIn-API-client#21]
Hi Team,

I have cloned this repository. After this i created sample php configuration file with my parameters 

```
<?php

/**
 * This demonstrates how to authenticate with LinkedIn and send api requests
 */

/*
 * First you need to make sure you've used composers auto load. You have is probably 
 * already done this before. You usually don't bother..
 */
require_once "vendor/autoload.php";
//require_once "src/HappyR/LinkedIn/LinkedIn.php";

$linkedIn = new HappyR\LinkedIn\LinkedIn('mykey', 'mykey');

if ($linkedIn->isAuthenticated()) {
    //we know that the user is authenticated now. Start query the API
    $user=$linkedIn->api('v1/people/~:(firstName,lastName)');
    echo "Welcome ".$user['firstName'];

    exit();
} elseif ($linkedIn->hasError()) {
    echo "User canceled the login.";
    exit();
}

//if not authenticated
$url = $linkedIn->getLoginUrl();
echo "<a href='$url'>Login with LinkedIn</a>";
```

After this when i open this file in browser i am getting error as 

```
Fatal error: Call to a member function get() on a non-object in /usr/share/nginx/www/lnk/vendor/illuminate/support/Illuminate/Support/Facades/Facade.php on line 208
```

Can any one please help me to get this problem fixed

**Comment by HMAZonderland** [comment]
How about when I do not wish to use Composer?

**Comment by Nyholm** [comment]
I don't understand the question. If you don't use composer, composer will not download the vendors and you will not have the problem in the first place. 

Would you mind elaborate your question?

**Comment by HMAZonderland** [comment]
You could manually download and `require_once` the needed files for inclusion instead of using Composer and its autoloader to do so. Which I'm doing for instance. I'm running into this problem as well. Now I simply excluded the Illuminate Session thingy, but there must be some reason you prefer to use this lib. Thats why I would like to know how to include this lib manually without using Composer or its Autoloader.

```php
// Use the Illuminate Session storage if it is available
        /*if (class_exists('\Illuminate\Support\Facades\Session')) {
            $this->storage = new IlluminateSessionStorage();
        } else {
            $this->storage = new SessionStorage();
        }*/
        $this->storage = new SessionStorage();
```

**Comment by Nyholm** [comment]
This line `if (class_exists('\Illuminate\Support\Facades\Session')) {` checks if the class exists. If it does (then you are using Illuminate already) we use the special IlluminateSessionStorage. Otherwise, just use the normal SessionStorage. 

Since you manually download the files you will not download the get the Illuminate library.

It seams like you already have downloaded the Illuminate lib and not really using it. Could that be the case?

**Comment by HMAZonderland** [comment]
`if (class_exists('\Illuminate\Support\Facades\Session'))` I do have the class but I guess its the wrong one because I'm getting `Fatal error: Call to a member function get() on a non-object in <$path> vendor/illuminate/support/Illuminate/Support/Facades/Facade.php on line 208` as well. And actually the `Facade.php` and `Session.php` class neither have the `get()` function. 

I do have `\Illuminate\Support\Facades\Session` installed. It came from this repo: https://github.com/illuminate/support but i'm guessing its not the same one?

**Comment by Nyholm** [comment]
That's the one. 

I can see that it is a problem here. You have the class loaded but you don't want to use the IlluminateSessionStorage. Can you see a good solution to this problem?

**Comment by HMAZonderland** [comment]
Well I would like to use that one, since you have your reason to do so. But when I do I get this error:

`Fatal error: Call to a member function get() on a non-object in <$path> vendor/illuminate/support/Illuminate/Support/Facades/Facade.php on line 208`

As above a fix is to remove the `vendor` folder and reinstall all dependencies by using `composer`. But I do not use Composer. I need to manually include the files needed. So how can I get this to work when i'm **not using composer**.

**Comment by Nyholm** [comment]
Thank you for highlighting a problem. You have loaded the `Illuminate\Support\Facades\Session` class but you do not which to use the `IlluminateSessionStorage`. Do you have a solution to this problem?

If you want to use the `Illuminate\Support\Facades\Session` for your sessions (like the Laravel framework does) I suggest you to read [its documentation](http://laravel.com/docs/5.0). It is out of scope for this lib and I'm not familiar with it.
